### PR TITLE
Update bundler

### PR DESCRIPTION
**Pull request by towanda**
Updates bundler to 2.2.7, which is needed for github actions.
https://github.com/Devex/article_json/runs/1804423185?check_suite_focus=true

### CODE REVIEW

**Comment by ifosch** [comment]
+1

**Comment by bbrassart** [comment]
+1 I think

**Review by miguelbernadi — APPROVED** [review]

**Comment by miguelbernadi** [comment]
+1

**Comment by miguelbernadi** [comment]
travis fails because it requires the old bundler version. Maybe it's time to also move the build to Github Actions and abandon travis?

**Pull request merged**
