### PR TITLE
Add amp elements base and text

### PR DESCRIPTION
**Pull request by towanda**
As a first step into adding amp export support, we add element base and element
text.

### CODE REVIEW

**Comment by christofdamian** [comment]
+1

**Comment by dsager** [comment]
@towanda 
there seems to be a let in your spec that's not used:
https://coveralls.io/builds/13454181/source?filename=spec%2Farticle_json%2Fexport%2Famp%2Felements%2Fbase_spec.rb

that's why the code coverage check fails...

**Comment by towanda** [comment]
@dsager removing it, thanks :)

**Comment by miguelbernadi** [comment]
+1

**Comment by ifosch** [comment]
+1

**Comment by dsager** [comment]
+1

**Pull request merged**
