### PR TITLE
Add embedded element: Facebook Video

### PR DESCRIPTION
**Pull request by dsager**

### CODE REVIEW

**Comment by nicolas-fricke** [comment]
+1

**Comment by EdLittle** [comment]
+1

**Comment by ifosch** [comment]
+1 I guess @nicolas suggestion for twitter RegEx, would be valid here too

**Comment by dsager** [comment]
@ifosch - in theory yes, but a little more overhead, as the id is generated in the parent class... I might refactor this all at once in the near future :)

**Pull request merged**
