### PR TITLE
Add CSS Parser

### PR DESCRIPTION
**Pull request by dsager**
This class allows the parsing of CSS code from google and offers methods to identify characteristics of specific class selectors.

This will later on be used to examine individual nodes of the HTML.

### CODE REVIEW

**Comment by ifosch** [comment]
Quite long PR ;)
Tests are failing... looks like something missing in the code or the tests... maybe this needs some mock for `ArticleJSON::Import`?

**Comment by miguelbernadi** [comment]
+1. I see there's no way to distinguish the case where only one class matches and all classes match. Is it not needed?

**Comment by ifosch** [comment]
+1

**Comment by dsager** [comment]
@miguelbernadi 
No, this is actually not needed. For example: we just have to check if a certain node has bold formatting, at that point we don't care if it's also italic.

**Pull request merged**
