### PR TITLE
Add image AMP export element (amp-img)

### PR DESCRIPTION
**Pull request by towanda**

### CODE REVIEW

**Comment by miguelbernadi** [comment]
+1

**Comment by ifosch** [comment]
+1

**Comment by dsager** [comment]
@towanda you forgot to add the element to the base class:
https://github.com/Devex/article_json/blob/master/lib/article_json/export/amp/elements/base.rb#L42

**Comment by towanda** [comment]
@dsager Added, thanks!

**Comment by dsager** [comment]
+1

**Comment by yaneq** [comment]
+1

**Comment by christofdamian** [comment]
+1

**Pull request merged**
