### PR TITLE
Add List and Heading AMP export element

### PR DESCRIPTION
**Pull request by towanda**

### CODE REVIEW

**Comment by miguelbernadi** [comment]
+1

**Comment by ifosch** [comment]
+1 but codeclimate is not happy @towanda

**Comment by towanda** [comment]
@ifosch yes, but nothing we can do about it. We talked about this  morning in the standup, and first we are going to do duplicating some code, and later refactoring.

**Comment by christofdamian** [comment]
+1 I think for this cases we can inherit from the HTML versions or point to them in the AMP exporter element configuration

**Comment by ifosch** [comment]
ah, ok, @towanda, now I understand manual merges I've been seeing :tongue:

**Comment by towanda** [comment]
@christofdamian good point, but at this point I feel more confident copying the code, and once that we have an implementation that's tested and then refactor.

**Comment by dsager** [comment]
+1

**Pull request merged**
