### PR TITLE
Readme small fix

### PR DESCRIPTION
**Pull request by towanda**

### CODE REVIEW

**Comment by ivandelrio** [comment]
+1

**Comment by miguelbernadi** [comment]
+1

**Comment by dsager** [comment]
+1

usually, it's a good idea to add this to a `.rspec` file, then you don't need to specify it. not sure if we should commit this instead of the readme change?! @towanda

**Comment by towanda** [comment]
@dsager I like much more the .rspec option, changing it

**Comment by dsager** [comment]
oops, I merged it already, you'll have to do another PR :)

**Pull request merged**
