### PR TITLE
html export for paragraphs & lists

### PR DESCRIPTION
**Pull request by dsager**

### CODE REVIEW

**Comment by towanda** [comment]
+1

**Comment by ivandelrio** [comment]
+1

**Comment by christofdamian** [comment]
I am not sure if I like creating html with nokogiri, this is pretty unreadable in my opinion.

**Comment by dsager** [comment]
@christofdamian 
I prefer using a tool for the job instead of generating HTML code via string concatenation.
But you are right that it is harder to understand. I discussed this with @nicolas-fricke and we tried to design the code in a way that allows for easy changes later on (most of the stuff happens in a few central methods like `create_element`).

**Pull request merged**
