### PR TITLE
Add Youtube and Vimeo embedded elemens

### PR DESCRIPTION
**Pull request by towanda**

### CODE REVIEW

**Comment by miguelbernadi** [comment]
+1

**Comment by nicolas-fricke** [comment]
:+1: looks good! :tv:

**Comment by dsager** [comment]
+1
Are these the only embed types supported by amp?

**Comment by towanda** [comment]
@dsager Nope, there's support for all the types we use, just wanted a not so big PR.

**Comment by christofdamian** [comment]
+1 we also have to find a way how to remember which amp extensions are used, for the required js includes

**Comment by towanda** [comment]
@christofdamian yes, I thought about adding a test for the parser, to check all which are included

**Pull request merged**
