### PR TITLE
Rubocop autocorrections

### PR DESCRIPTION
**Pull request by damiendillon**
Enhance code quality with Rubocop autocorrections.

### CODE REVIEW

**Comment by damiendillon** [comment]
The commit descriptions should perhaps be the commit titles. Apologies for the extra clicks just to read them.

**Comment by ozgun** [comment]
Looks good, thanks :)

**Comment by agustibr** [comment]
👍️ Thanks!

**Comment by EdLittle** [comment]
+1

i thought we liked trailing commas 🤔

**Comment by damiendillon** [comment]
> +1
> 
> i thought we liked trailing commas 🤔

Is it not that we have them in hashes but not arrays?

**Comment by dsager** [comment]
I would actually be in favor of adjusting the rules, so that both Hashes and Arrays have trailing commas, like we do in our main codebase! Any thoughts on this before we move ahead?

**Comment by ozgun** [comment]
My vote is for the consistency. Since our main codebase has trailing commas, I'd say we should follow the same rule here as well.

**Comment by damiendillon** [comment]
Sure, I will remove the trailing commas commit.

**Comment by damiendillon** [comment]
Dropped the commit with the removal of trailing commas in arrays.

**Pull request merged**
