### PR TITLE
Add twitter amp support

### PR DESCRIPTION
**Pull request by towanda**

### CODE REVIEW

**Comment by miguelbernadi** [comment]
+1

**Comment by christofdamian** [comment]
+1

**Comment by towanda** [comment]
[B]

**Comment by yaneq** [comment]
+1

**Comment by dsager** [comment]
@towanda
Why are you reverting the symbols? much nicer than the hash rockets :(

**Comment by towanda** [comment]
@dsager because they are not compatible with ruby 2.1

**Comment by dsager** [comment]
@towanda
Not a problem, see https://github.com/Devex/article_json/blob/master/article_json.gemspec#L26

**Pull request merged**
