### PR TITLE
Add AMP TextBox Element

### PR DESCRIPTION
**Pull request by towanda**

### CODE REVIEW

**Comment by christofdamian** [comment]
+1 shall we kick codeclimate out?

**Comment by dsager** [comment]
+1
I like to have the code climate, like this at least you have to double check if you are fine with the duplication...

**Comment by towanda** [comment]
I agree with keeping CC, this way we know it.

**Comment by miguelbernadi** [comment]
+1

**Comment by nicolas-fricke** [comment]
+1 Looks good :)

**Pull request merged**
