### PR TITLE
Basic structure

### PR DESCRIPTION
**Pull request by dsager**
This PR sets up the basic structure for the gem to get things started, most of this is boilerplate.

### CODE REVIEW

**Comment by christofdamian** [comment]
+1 I expected it to be renamed to something that doesn't clash with the JS version

**Comment by dsager** [comment]
@christofdamian The idea is to a) make clear that this is the "ruby version" and that the format is slighty different and b) try to stay as close as possible to the "JS version"...

**Comment by towanda** [comment]
+1

**Comment by miguelbernadi** [comment]
+1, Is the project open?

**Comment by ifosch** [comment]
+1 not sure how many +1s this project require ;P

**Comment by dsager** [comment]
it's not part of plus-pull yet, @ifosch - accepting the PR manually now...

**Pull request merged**
