### PR TITLE
Fix facebook embedded url

### PR DESCRIPTION
**Pull request by towanda**
The facebook video url was not absolute, and this caused the iframe not to load.

### CODE REVIEW

**Comment by miguelbernadi** [comment]
+1

**Comment by nicolas-fricke** [comment]
:+1: Good catch!

**Comment by ivandelrio** [comment]
+1

**Comment by bbrassart** [comment]
+1

**Comment by dsager** [comment]
+1
would be good, if you can fix this as well for the youtube videos (it works now, but better safe than sorry). See https://github.com/dsager/article_json/commit/4708dad044a946546455d3e29c61f26a4361494e

**Comment by towanda** [comment]
@dsager sure!

**Pull request merged**
